# Generated by Django 4.1.5 on 2023-02-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_profilecomment_user_profilepic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
